### ISSUE TITLE
Problems synching media capture video and audio clips

### ISSUE THREAD

**Issue by tewksbum** [aws-samples/amazon-chime-media-capture-pipeline-demo#1]
In our /video folder we have a dump of clips from all attendees.  We are trying to isolate a single attendee for the duration of the meeting and marry that to the /audio output.  

We are struggling to synch the audio and video clips.  Generally speaking the audio recordings start before the video and run longer.  Trying to align these is proving problematic.  Closest we've come is using something like:

ffmpeg.exe -ss 00:00:10  -t 5 -i "video.mp4" -ss 0:00:01 -t 5 -i "music.m4a" -map 0:v:0 -map 1:a:0 -y out.mp4

but don't know what values to put for -ss... nor if "-t 1" is refined enough... does it need to go to ms?

It seems this should be a much easier step than its turning out to be.

**Comment by tewksbum** [comment]
reviewing... 

https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/blob/main/src/processLambda/process.py

bit bleary eyed atm, but I see this is joining up the audio files... but not touching the video?

**Comment by albrich-me** [comment]
We did the following:
