### ISSUE TITLE
Content Share capture quality

### ISSUE THREAD

**Issue by gustavofamorim** [aws-samples/amazon-chime-media-capture-pipeline-demo#10]
Hi, Team. 

It's great to see this project and the new capture capability launched. It is way more professional and relyable than the previously published recording demo in https://github.com/aws-samples/amazon-chime-sdk-recording-demo.

When I start a capture the final files aways have 1280x720, even when the content share have greather resolutions such as 1920x1080 or 2560x1440.

Looking into the SDK and the options provided, I wasn't able to find some way to define the video quality.

Is it possible to achieve a better quality by increasing the bitrate and  have less compression?

**Comment by achris** [comment]
Since this issue was created, we have changed the content share output to 1080p and increased the bitrate for both camera and content streams.  I'm closing this ticket since there hasn't been any activity in some time, but feel free to reach out if you need further help.
