### ISSUE TITLE
attendeeId missing when clicking 'Join'

### ISSUE THREAD

**Issue by arunzeli** [aws-samples/amazon-chime-media-capture-pipeline-demo#112]
<img width="779" alt="image" src="https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/142459603/2ee72388-1c86-42ed-8762-c41509ed9771">

I deployed successfully but when I click the join button, nothing happens and I am getting the above error. Anyone facing similar issues?

**Comment by arunzeli** [comment]
I fixed it by adding the roles

aws iam create-service-linked-role --aws-service-name transcription.chime.amazonaws.com

aws iam create-service-linked-role --aws-service-name mediapipelines.chime.amazonaws.com

**Comment by schuettc** [comment]
Yes, creating the SLRs during the deployment was causing issues with multiple deployments, so I had removed it.  Those SLRs are required though.
