### ISSUE TITLE
Media Concatenation Pipeline Naming Inconsistency

### ISSUE THREAD

**Issue by tomlson2** [aws-samples/amazon-chime-media-capture-pipeline-demo#133]
The concat bucket directory/file names do not match neither the MeetingId (this is convention for the capture bucket) nor the initial MediaPipelineId returned from invoking the Media Pipeline. Is this an issue with the way that the CreateMediaCapturePipelineCommand works?

**Comment by niborkar** [comment]
Can you clarify a bit more? Are you trying to use CreateMediaCapturePipeline or CreateMediaConcatenationPipeline API?

**Comment by tomlson2** [comment]
> Can you clarify a bit more? Are you trying to use CreateMediaCapturePipeline or CreateMediaConcatenationPipeline API?

I am using both, but my problem seems to be with the CreateMediaConcatenationPipeline API.

In eventBridge.ts the startConcat function triggered by Amazon EventBridge (when the media capture pipeline ends) invokes the CreateMediaConcatenationPipeline. From my understanding, this should be storing the files in the concat bucket with the directory/file names in the same convention of the capture bucket, however it seems to be creating and storing these files under a new UID. 

The clarification I need is where does the UID/Name come from for the items in the concat bucket?

Hopefully this illustrates my issue and the expected behavior a little better:
<img width="740" alt="PostMeeting" src="https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/86486152/809a6ca6-4471-4e0f-879f-5ad9c5d5f9ec">

**Comment by schuettc** [comment]
https://docs.aws.amazon.com/chime-sdk/latest/dg/concat-folder-structure.html

It's based on the media pipeline id.

**Comment by tomlson2** [comment]
> https://docs.aws.amazon.com/chime-sdk/latest/dg/concat-folder-structure.html
> 
> It's based on the media pipeline id.

This is what I had originally understood, but following the trail of original media pipeline creation through the creation of the media concat pipeline, the concatenated files do not exist under the given media pipeline id.

Log showing the media pipeline id after creating a meeting / media pipeline:
![image](https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/86486152/1024b692-3a63-4627-a8f1-3723836d15f8)

createConcatPipelineParams log from the startConcat function (eventBridge.ts/post-call lambda):
![image](https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/86486152/a0608472-c313-4698-86f7-f848a5a31cc4)

No match in the concat bucket. The concatenated data does exist, but under a different unique id.
![image](https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/86486152/4cfcd8bf-22a5-4e8f-b6e6-982f60fec8a6)

**Comment by tomlson2** [comment]
> https://docs.aws.amazon.com/chime-sdk/latest/dg/concat-folder-structure.html
> 
> It's based on the media pipeline id.

This is what I had originally understood, but following the trail of original media pipeline creation through the creation of the media concat pipeline, the concatenated files do not exist under the given media pipeline id.

Log showing the media pipeline id after creating a meeting / media pipeline:
![Screenshot 2024-04-03 125448](https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/86486152/b0e09526-7685-4a77-9783-9df832ad8ad0)

createConcatPipelineParams log from the startConcat function (eventBridge.ts/post-call lambda):
![Screenshot 2024-04-03 130713](https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/86486152/1e2af2b9-9240-488c-a72d-06ddd7f24d07)


No match in the concat bucket. The concatenated data does exist, but under a different unique id.
![Screenshot 2024-04-03 125329](https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/assets/86486152/ed8d409c-1f95-4963-848e-6183b73e9759)

**Comment by schuettc** [comment]
Can you check it against the concat pipeline id?  That looks like the capture pipeline id.
