### ISSUE TITLE
Question on Media Capture Stream

### ISSUE THREAD

**Issue by euro-bYte** [aws-samples/amazon-chime-media-capture-pipeline-demo#136]
Our team wants to confirm if the video capture resolution scales up to HD resolution or starts off as HD and the video "buffers" in the quality? 

We want to assess the limitations of the media capture pipeline and to know how to work around it - specifically those related to resolution and quality.

Thanks in advance to anyone who can assist

**Comment by MingcongQi** [comment]
Media capture will scale up to HD resolution.

**Comment by euro-bYte** [comment]
So just to confirm the video for example could start off looking SD but eventually scale to HD over a period of time?

**Comment by MingcongQi** [comment]
No, the media capture resolution is fixed. if you select HD resolution,  media capture will scale up to HD if receiving SD and scale down to HD if receiving FHD.

**Comment by euro-bYte** [comment]
Thank you very much on this!!
