### ISSUE TITLE
We need to have a single output mp4 file that contains both audio and video of a meeting where more than 1 attendee is sharing the screen and talking.

### ISSUE THREAD

**Issue by MohammedAbadi1991** [aws-samples/amazon-chime-media-capture-pipeline-demo#15]

**Comment by tenge-amzn** [comment]
thanks for the suggestion. We will evaluate the feature, meanwhile, you can achieve this by post processing the capture artifacts - combining the desired media streams into one file after media capture is completed.

**Comment by schuettc** [comment]
Updated with new version that include concatenation pipeline.  

https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/pull/32
