### ISSUE TITLE
Timestamp '1970-01-01T00:00:00.000+00:00' in the AttendeeVideoLeft event

### ISSUE THREAD

**Issue by vknaisl** [aws-samples/amazon-chime-media-capture-pipeline-demo#16]
If you stop the recording before you turn off screen sharing or participant's video, timestamps at the `AttendeeVideoLeft` events for screen sharing and participant's video are set to the `1970-01-01T00:00:00.000+00:00`.

**Comment by niborkar** [comment]
This should be fixed now. Let us know if you still see the issue.

**Comment by vknaisl** [comment]
Thanks, it seems working now :-)
