### ISSUE TITLE
Stop and resume recording

### ISSUE THREAD

**Issue by 20vitality12** [aws-samples/amazon-chime-media-capture-pipeline-demo#18]
Can we stop and resume recording or we should stop recording at all and start again? The recording will continue in the same folder and will not be overwritten, what was there?
(Also now processLambda merge only audio files or video too?)

**Comment by ajselvar** [comment]
There is currently no option to pause and resume a recording. Stopping and starting a recording again will behave same as pause and resume. The older artifacts will not be deleted/over-written.

**Comment by achris** [comment]
We haven't heard from you.  We're closing this ticket, please reopen if the issue hasn't been resolved.
