### ISSUE TITLE
Slow Video and Audio loosing

### ISSUE THREAD

**Issue by LFiungano14** [aws-samples/amazon-chime-media-capture-pipeline-demo#2]
The output file has no audio, the video is slow and is longer than the sum of the videos. I am using the .mp4 videos in meetingId / audio

**Comment by tenge-amzn** [comment]
Hi there,
Could you provide more information? What's the meeting Id?

**Comment by schuettc** [comment]
We've updated the ffmpeg to use a different process.  Can you take a look at the latest version and see if that helps? https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/commit/806388983857ac3cc28bf0143dd8a132301889e4
