### ISSUE TITLE
Cay you please provide process lambda code for concatenate ActiveSpeaker video and Share screen in to single mp4 file

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws-samples/amazon-chime-media-capture-pipeline-demo#20]
Hi

Can you please provide process lambda code for concatenating Active speaker video and audio and also Share screen content into a single mp4 file?

Currently, I get Active Speaker and Share video (if the video contains audio) in the final concatenate file of the audio folder.
but need to concatenate Share screen (audio is mute) into a final merged file of the audio.

**Comment by tenge-amzn** [comment]
https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo

We have a sample code here to concatenate the file.
