### ISSUE TITLE
Need to recording of all attendees video and audio as well single attendee content sharing 

### ISSUE THREAD

**Issue by mvaghasia** [aws-samples/amazon-chime-media-capture-pipeline-demo#22]
Hello,
We would like capture (recording) audio and video of all attendees and single attendee content sharing as one recording file.

As per document (https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/) ,by default media capture pipeline capture video of active speaker.  

Can you provide details how to turn on capture (recording) audio and video of all attendees and single attendee content sharing ?

Also can you pleases provide steps (such as invoke Process Lambda function from S3 trigger ) to concatenating all those audios/videos and content sharing video files as one recording file instead of multiple files.

**Comment by vijayamin83** [comment]
Do we have any update on this?

I am also facing the same issue

**Comment by vijayamin83** [comment]
Is there any update on this?

**Comment by tenge-amzn** [comment]
>Can you provide details how to turn on capture (recording) audio and video of all attendees and single attendee content sharing ?
You can check out the blog post:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

Turning on video and content share in the request to have all the attendee and content share recorded.

For concatenation, you can use ffmpeg or gstreamer. We will have a turnkey solution to do the concatenation soon. Currently we're working on it.

**Comment by schuettc** [comment]
Stale
