### ISSUE TITLE
Deploy failed and got error: "'MemorySize' value failed to satisfy constraint

### ISSUE THREAD

**Issue by msundiitalk** [aws-samples/amazon-chime-media-capture-pipeline-demo#28]
Hi 

I try to deploy the demo flow up the README, when I run `./deploy.sh`, I got below error:
![image](https://user-images.githubusercontent.com/39921674/165828153-7e7ca4b7-1d9d-4322-9a4b-c827e63a405b.png)

why this error happen and how to solve it?	
	
![image](https://user-images.githubusercontent.com/39921674/165827466-eae329f5-d08c-42c6-9fa6-24af21db54c3.png)
![image](https://user-images.githubusercontent.com/39921674/165827496-b8438db1-dc4a-4ae3-8532-c641ea634a34.png)

**Comment by schuettc** [comment]
What region are you deploying to?  It looks like there might be a limit in some regions on memory size of the Lambda.
Could you try deploying to us-east-1?

https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-supports-10gb-memory-6-vcpu-cores-lambda-functions/

**Comment by msundiitalk** [comment]
Yes, I am using `woohelps` profile with `us-east-1` as default region.

![image](https://user-images.githubusercontent.com/39921674/165837292-18d03111-c517-4e7b-9564-9c7dea2f51bb.png)
