### ISSUE TITLE
Is there any way to replay the captured content by front end

### ISSUE THREAD

**Issue by austinpan** [aws-samples/amazon-chime-media-capture-pipeline-demo#29]
We've tried to concat the captured content of the presenter, attendee, and share screen. 
But found the result is not good as we thought. We want to show all content include messages in the meeting.
Is there any way to replay the captured content by front end, then we can record all of them again on demand

**Comment by tenge-amzn** [comment]
Hi @austinpan 
Can you elaborate what's the specification that you like to see? We do have some features that's currently in private beta, but want to make sure.

**Comment by austinpan** [comment]
@tenge-amzn  Thanks for the reply.

https://aws.amazon.com/tw/blogs/business-productivity/amazon-chime-sdk-compositing-videos-from-media-capture-pipelines/
We use this example to concat videos before.
Since the FFmpeg concat video is not good as we thought. So We think maybe reply them is much more suitable.

We want to replay the recorded video of the presenter, attendee, and share screen on the web page which is placed by the front end. And use the play and pause to control them ( which are 5-second segments arranged by the time ).
We will record the content of the replay web page again when we need it.

**Comment by tenge-amzn** [comment]
do you want the all attendee's video in a single video tile, or split?

**Comment by austinpan** [comment]
Both are acceptable. Split tiles would be better.

**Comment by tenge-amzn** [comment]
I still do not fully understand what's your goal. If you want to play it on a webpage - you need to build your frontend page.

**Comment by austinpan** [comment]
OK. We will build our own playback web page. Thanks

**Comment by schuettc** [comment]
Updated with new version that includes playback option

https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/pull/32
