### ISSUE TITLE
No way to display the AttendeeId or ExternalUserId of the participant on the recording file.

### ISSUE THREAD

**Issue by kodai305** [aws-samples/amazon-chime-media-capture-pipeline-demo#31]
## What we tried and current status

The following document and others confirm the operation of converting data captured with MediaCapturePipeline to a single mp4 file.
When I ran it as described in the article, I confirmed that the Video and Audio information for all participants (those with Video enabled) were combined.
https://aws.amazon.com/jp/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

## What we are having trouble with

Since there is no attendee information such as attendee name(or AttendeeId) in the Video displayed in the recording file, it is impossible to distinguish who is who in which Video data.
I thought that if I specified SourceConfiguration, it would show AttendeeId, etc., but it did not behave as expected.

Is there any solution?
If possible, I would also like to provide information on who has Video turned off.

**Comment by xuesichao** [comment]
Close this one in favor of https://github.com/aws/amazon-chime-sdk-js/issues/2432. Thanks for reporting the issue.
