### ISSUE TITLE
deploy issue

### ISSUE THREAD

**Issue by EgorMaksimenko** [aws-samples/amazon-chime-media-capture-pipeline-demo#38]
Hello.
Now I take issue when type 'yarn launch'
---------------------------------------------------------------------------------------------------------------------------------------
AmazonChimeSDKWithTranscribe |  2/74 | 8:59:17 AM | CREATE_FAILED        | AWS::IAM::ServiceLinkedRole                     | mediapipeline/MediaPipelineSLR (mediapipelineMediaPipelineSLRBBA73712) SLR [AWSServiceRoleForAmazonChimeSDKMediaPipelines] already exists but has a different description: [Allows Chime SDK media pipelines to access AWS services on your behalf.]. Please verify your SLR use case. If you are sure the use case is correct please modify your CloudFormation template and keep SLR description consistent.

mazonChimeSDKWithTranscribe |  2/74 | 8:59:18 AM | CREATE_FAILED        | AWS::IAM::Role                                  | infrastructure/ChimeSDKMeetingWithTranscribeAPI/CloudWatchRole (infrastructureChimeSDKMeetingWithTranscribeAPICloudWatchRoleD72926DA) Resource creation cancelled
------------------------------------------------------------------------------------------------------------------------------------------

could you figure out about this issue?

**Comment by schuettc** [comment]
This appears to be an issue when deploying to an account with an existing SLR.  Information on SLRs here: https://docs.aws.amazon.com/chime-sdk/latest/dg/create-pipeline-role.html

Solution is to either [remove the existing SLR](https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html#delete-service-linked-role) and re-deploying, or removing the SLR from the existing deploy here: https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/blob/90eb780962bf9877373c97e16d826dd9414cda09/src/media-pipeline.ts#L32-L34
