### ISSUE TITLE
When using the demo. file processedAudio.mp4 only audio. Not video. I want when stop meeting have one video perfect ? Please help me

### ISSUE THREAD

**Issue by phongdat90** [aws-samples/amazon-chime-media-capture-pipeline-demo#4]
Id Meeting: 0d80b376-7f72-41ec-894f-350541470706
I am using demo. but when i end the call. There is no complete video file in the S3 repository. i am very wholesale? please let me know for a complete video?

**Comment by achris** [comment]
Hi, this demo does not join the files in the "video/" directory in S3.  It only joins the files in "audio" (which might also contain the video corresponding to the attendee speaking depending on your configuration).

If you want to join the video files, you could modify the code in https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/blob/main/src/processLambda/app/app.py

**Comment by phongdat90** [comment]
thankies @achris. great!
I'm not python savvy. It would be great if you could join the demo video

**Comment by tenge-amzn** [comment]
@phongdat90 
Could you elaborate what's your desired result? Do you want a combined artifact from merging `vide/*.mp4` ? You can run ffmpeg command line or other language bindings.

**Comment by phongdat90** [comment]
thankies @tenge-amzn . when end metting I want to have file merge video and audio.

**Comment by tenge-amzn** [comment]
Hi @phongdat90 
As mentioned above, you can use ffmpeg to merge them. 

However, to combine everything, more factors need to be considered:
what's the layout for different video tile(gallery view vs speaker view?); how is the screenshare displayed versus other video tiles; what if someone enabled/disable video in the middle of the meeting?

**Comment by schuettc** [comment]
https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/pull/32

New update includes media concatenation pipeline to create a single output.
