### ISSUE TITLE
thanks for share. But I am using Chime SDK. I want a complete video with both picture and sound. please support me

### ISSUE THREAD

**Issue by nguyengiap6886** [aws-samples/amazon-chime-media-capture-pipeline-demo#6]
I want a complete video with both picture and sound. please support me!!
Process that output into a complete video file

**Comment by achris** [comment]
Hi, this demo does not join the files in the "video/" directory in S3. It only joins the files in "audio" (which might also contain the video corresponding to the attendee speaking depending on your configuration).

You could modify the code in https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/blob/main/src/processLambda/app/app.py 

The process is the same, however if you have a "video" directory, the files are separated by attendee ID so you would need to choose which files you want to join, and you would need to tell ffmpeg to take the audio from a different file.  You can refer to https://www.ffmpeg.org/ffmpeg.html for how to use the different options.  The options used in the demo can be found on lines 44 and 51.

**Comment by nguyengiap6886** [comment]
thank you. I will look for many libraries ffmpeg. for merge all file audio and video. The end customer only needs a single file full of video and audio

**Comment by schuettc** [comment]
https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/pull/32

New update includes media concatenation pipeline to create a single file output.
