### ISSUE TITLE
Module not found: Can't resolve './cdk-outputs.json'

### ISSUE THREAD

**Issue by mliu0515** [aws-samples/amazon-chime-media-capture-pipeline-demo#8]
Not sure if I missed any steps, but I tried to follow the instruction, and when I finally ran "yarn start", there is a complier error that says:

**./src/App.js
Module not found: Can't resolve './cdk-outputs.json' in '~\Desktop\amazon-chime-media-capture-pipeline-demo\client\src'**

How can I solve this? Let me know if I need to provide more information.

**Comment by schuettc** [comment]
Did the cdk deployment run correctly?  That should be output from the cdk deployment that the client uses to know what API gateway url to use.
